dist: xenial
sudo: true
language: generic
services:
  - postgresql
addons:
  postgresql: "10"
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - pgdg-xenial
    packages:
      - postgresql-10
      - postgresql-10-postgis-2.4
      - postgresql-10-postgis-2.4-scripts
env:
  - PGPORT=5433
before_script:
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 7FCC7D46ACCC4CF8
  - sudo sh -c 'echo "deb https://apt-archive.postgresql.org/pub/repos/apt/ xenial-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
  - sudo apt-get update -qq
  - sudo service postgresql stop
  - sudo service postgresql start 10
  - sleep 2
  - psql -U postgres -p 5433 -h localhost -c "CREATE EXTENSION IF NOT EXISTS postgis;"
script:
  - psql -U postgres -p 5433 -h localhost -c "SELECT postgis_full_version();"
cache:
  apt: true
